Use Coroutines for TickTasks
Skytils/SkytilsMod pull request #368
Opened 2023-04-01 12:26 UTC by My-Name-Is-Jeff

Could completely remove ticktask maybe?

2023-04-02 22:07 UTC, Sychic requested changes
The behavior changes from running every tick to running every game loop

2023-04-02 22:07 UTC, Sychic commented on src/main/java/gg/skytils/skytilsmod/mixins/transformers/MixinMinecraft.java
Personally not a fan of mixing in and adding it

2023-04-02 22:07 UTC, Sychic commented on src/main/kotlin/gg/skytils/skytilsmod/utils/Utils.kt
> +import kotlin.time.Duration.Companion.milliseconds
Unnecessary import?

2023-04-02 22:07 UTC, Sychic commented on src/main/kotlin/gg/skytils/skytilsmod/utils/tasks/TickTask.kt
> +    val task: (CoroutineContext) -> T
Could add a secondary constructor that takes a lambda with no args

2023-04-02 22:07 UTC, Sychic commented on src/main/kotlin/gg/skytils/skytilsmod/utils/tasks/TickTask.kt
>      } catch (t: Throwable) {
Probably want to catch `CoroutineCancellationException` separately

2023-04-02 22:26 UTC, My-Name-Is-Jeff commented
> The behavior changes from running every tick to running every game loop

How does coroutine work? I think they accomplish the same thing unless Minecraft is running behind on ticks

2023-04-02 22:28 UTC, Sychic commented
> > The behavior changes from running every tick to running every game loop
> 
> How does coroutine work? I think they accomplish the same thing unless Minecraft is running behind on ticks

Well since the coroutine scope has a MC executor as a dispatcher, it's going to queue the tasks there. AFAICT, MC's `addScheduledTask` executes every game loop as opposed to every game tick.

2023-04-02 22:30 UTC, My-Name-Is-Jeff commented
> > > The behavior changes from running every tick to running every game loop
> > 
> > 
> > How does coroutine work? I think they accomplish the same thing unless Minecraft is running behind on ticks
> 
> Well since the coroutine scope has a MC executor as a dispatcher, it's going to queue the tasks there. AFAICT, MC's `addScheduledTask` executes every game loop as opposed to every game tick.

Delay behavior should be the same if each tick takes 50ms right? Should be fine because ticks also happen in game loop

2023-04-02 22:32 UTC, Sychic commented
> > > > The behavior changes from running every tick to running every game loop
> > > 
> > > 
> > > How does coroutine work? I think they accomplish the same thing unless Minecraft is running behind on ticks
> > 
> > 
> > Well since the coroutine scope has a MC executor as a dispatcher, it's going to queue the tasks there. AFAICT, MC's `addScheduledTask` executes every game loop as opposed to every game tick.
> 
> Delay behavior should be the same if each tick takes 50ms right? Should be fine because ticks also happen in game loop

I think game loops aren't aligned to ticks since game loops are also where the game renders each frame. The delay behavior makes sense but it wouldn't be synced to a tick to begin with.

2024-02-29 23:59 UTC, My-Name-Is-Jeff commented
Superseded by 7a741404e010ba19f6b52477341b5720e31c04a7

2024-02-29 23:59 UTC, closed without merging