Fixed item stack copy
Skytils/SkytilsMod pull request #484
Opened 2024-05-19 20:49 UTC by hannibal002

Fixed calling `ItemStack.copy()` too often unnecessary.

In `MiningFeatures.onDrawSlot` we are calling `val item = event.slot.stack`, even outside the HOTM inventories. This causes the injected  `MixinSlot` to call `markTerminalItems`. In here, we create a copy of the item stack before checking if the slot number is part of `SelectAllColorSolver` or `StartsWithSequenceSolver`.

2024-05-19 21:15 UTC, My-Name-Is-Jeff approved these changes

2024-05-19 22:31 UTC, Sychic requested changes

2024-05-19 22:31 UTC, Sychic commented on src/main/kotlin/gg/skytils/skytilsmod/features/impl/mining/MiningFeatures.kt
> +            if (ItemUtil.getItemLore(item).any { it == "§c§lDISABLED" }) {
Might as well inline `item` here.

2024-05-19 22:31 UTC, Sychic commented on src/main/kotlin/gg/skytils/skytilsmod/mixins/hooks/inventory/SlotHook.kt
> +    if (!original.isItemEnchanted && (SelectAllColorSolver.shouldClick.contains(slot.slotNumber) ||
Same here

2024-05-20 09:52 UTC, hannibal002 commented on src/main/kotlin/gg/skytils/skytilsmod/mixins/hooks/inventory/SlotHook.kt
> +    if (!original.isItemEnchanted && (SelectAllColorSolver.shouldClick.contains(slot.slotNumber) ||
`original` gets used two times.
![image](https://github.com/Skytils/SkytilsMod/assets/24389977/4f98a165-21d6-4c9f-885f-af2ef8dfad62)

2024-05-27 16:15 UTC, Sychic approved these changes

2024-06-13 17:15 UTC, merged