add /skytilsremovehollowwaypoint command
Skytils/SkytilsMod pull request #49
Opened 2021-07-16 07:42 UTC by DeDiamondPro

2021-07-16 15:34 UTC, Sychic reviewed
Couldn't you make it one command with arguments?

2021-07-16 15:35 UTC, DeDiamondPro commented
> Couldn't you make it one command with arguments?

Since I'm also adding something so you can view them all yeah sure I can do that

2021-07-18 02:36 UTC, My-Name-Is-Jeff requested changes

2021-07-18 02:36 UTC, My-Name-Is-Jeff commented on src/main/kotlin/skytils/skytilsmod/commands/HollowWaypointCommand.kt
> +import tv.twitch.chat.Chat
What's this for?

2021-07-18 02:36 UTC, My-Name-Is-Jeff commented on src/main/kotlin/skytils/skytilsmod/commands/HollowWaypointCommand.kt
>      override fun processCommand(sender: ICommandSender?, args: Array<out String>?) {
both shouldn't be null, remove the null safe param type

2021-07-18 02:36 UTC, My-Name-Is-Jeff commented on src/main/kotlin/skytils/skytilsmod/features/impl/mining/MiningFeatures.kt
> +import javax.print.DocFlavor
What is this for?

2021-07-18 02:36 UTC, My-Name-Is-Jeff commented on src/main/kotlin/skytils/skytilsmod/features/impl/mining/MiningFeatures.kt
> +import kotlinx.coroutines.delay
When do you use coroutines?

2021-07-18 02:36 UTC, My-Name-Is-Jeff commented on src/main/kotlin/skytils/skytilsmod/features/impl/mining/MiningFeatures.kt
> +            mc.textureManager.bindTexture(ResourceLocation("skytils", "crystalhollowsmap.png"))
maybe make the resource location a constant?

2021-07-18 03:15 UTC, My-Name-Is-Jeff approved these changes

2021-07-18 03:20 UTC, Sychic approved these changes
lgtm

2021-07-18 03:24 UTC, merged