feat: Run breakdown
Skytils/SkytilsMod pull request #499
Opened 2024-09-13 20:24 UTC by TakoTheDev

- don't know how to test for secrets/rooms
- I think this is ugly, but no idea how else to do it (open for suggestions)
![image](https://github.com/user-attachments/assets/437648a1-4942-4239-b6fc-87ad9573d622)

- azoo says no to terminals and levers, but idc

2024-09-13 20:37 UTC, TakoTheDev commented
no idea why it decided to delete `src/main/kotlin/gg/skytils/skytilsws/shared/structs/BoundingBox.kt` and `src/main/kotlin/gg/skytils/skytilsws/shared/structs/CHWaypointType.kt`

2024-09-14 01:37 UTC, My-Name-Is-Jeff requested changes

2024-09-14 01:37 UTC, My-Name-Is-Jeff commented on src/main/kotlin/gg/skytils/skytilsmod/listeners/DungeonListener.kt
> +                                    WSClient.sendPacketAsync(C2SPacketDungeonRoomSecret(SBInfo.server ?: return@setFoundSecrets, room.mainRoom.data.name, sec, mc.thePlayer.name))
what is the point of this? two players can have the same update at the same time and can be in the same room at the same time

additionally the server is aware of the sender of the packet

2024-09-14 10:53 UTC, TakoTheDev commented
I can't really test rooms and secrets, since I can't keep a websocket connection for some reason, so would be nice if someone else could test it <3

2024-09-20 03:42 UTC, My-Name-Is-Jeff commented
> I can't really test rooms and secrets, since I can't keep a websocket connection for some reason, so would be nice if someone else could test it <3 (Even on the version in Releases, I think it's internet issue)

make sure you did not  modify packets

2025-05-30 21:30 UTC, closed without merging