feat: scalable ch player arrow
Skytils/SkytilsMod pull request #521
Opened 2024-10-28 00:12 UTC by Kemmisch

make ch player arrow scalable through a config option

2024-11-03 06:28 UTC, My-Name-Is-Jeff requested changes
also put it in the translation file

2024-11-03 06:28 UTC, My-Name-Is-Jeff commented on src/main/kotlin/gg/skytils/skytilsmod/core/Config.kt
> +        description = "Scale the arro indicating the arrorw on the crystal hollows map",
several typos

2024-11-03 12:10 UTC, Kemmisch commented
> also put it in the translation file
should i leave CN & TW blank, or leave the english in there?

2024-11-05 04:40 UTC, My-Name-Is-Jeff requested changes

2024-11-05 04:40 UTC, My-Name-Is-Jeff commented on src/main/kotlin/gg/skytils/skytilsmod/core/Config.kt
> +        addDependency("crystalHollowsMapPlayerScale","crystalHollowMap")
style: add space
```suggestion
        addDependency("crystalHollowsMapPlayerScale", "crystalHollowMap")
```

2024-11-05 04:40 UTC, My-Name-Is-Jeff commented on src/main/kotlin/gg/skytils/skytilsmod/core/Config.kt
> +
style: remove spaces

2024-11-05 04:40 UTC, My-Name-Is-Jeff commented
> > also put it in the translation file
> 
> should i leave CN & TW blank, or leave the english in there?

You can just leave it blank I believe and it should default to English

2025-01-27 21:04 UTC, merged